name: Docker Image CI

on:
  push:
    branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      id: GSV
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
      
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        APP_VERSION: ${{ steps.GSV.ouputs.version }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        APP_VERSION: ${{ steps.GSV.ouputs.version }}
      run: |
        docker build --file Dockerfile --tag $DOCKER_USER/docker-graphql:$APP_VERSION .
        docker build --file Dockerfile --tag $DOCKER_USER/docker-graphql:latest .        
        
    - name: Push Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        APP_VERSION: ${{ steps.GSV.ouputs.version }}
      run: |
        docker push $DOCKER_USER/docker-graphql:$APP_VERSION
        docker push $DOCKER_USER/docker-graphql:latest

